# Generated by Django 5.0.3 on 2024-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='port_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='targets',
            name='target_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='team_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
